# Generated by Django 3.0.4 on 2020-03-28 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64, null=True)),
                ('created_by', models.CharField(max_length=64, null=True)),
                ('police', models.CharField(max_length=20)),
                ('health_dpt', models.CharField(max_length=20)),
                ('health_dpt_address', models.CharField(max_length=20)),
                ('police_dpt_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('Neighbourhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('status', models.TextField(blank=True, max_length=254)),
                ('profile_picture', models.ImageField(default='default.png', upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hoodnews.Neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsn_name', models.CharField(max_length=64, unique=True)),
                ('bsn_email', models.EmailField(max_length=64, unique=True)),
                ('Neighbourhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodnews.Neighbourhood')),
            ],
        ),
    ]
