# Generated by Django 3.0.4 on 2020-04-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodnews', '0003_auto_20200403_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Neighbourhood',
            new_name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='health_dpt',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='health_dpt_address',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='police',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='police_dpt_address',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police', models.CharField(max_length=20)),
                ('health_dpt', models.CharField(max_length=20)),
                ('health_dpt_address', models.CharField(max_length=20)),
                ('police_dpt_address', models.CharField(max_length=20)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodnews.Neighbourhood')),
            ],
        ),
    ]
