# Generated by Django 3.0.4 on 2020-04-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodnews', '0004_auto_20200404_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Neighbourhood_id',
            new_name='neighbourhood_id',
        ),
    ]
